### ISSUE TITLE
OSError: Could not locate nacl lib

### ISSUE THREAD

**Issue by robomotic** [threema-ch/threema-msgapi-sdk-python#57]
Hi there,
just installed via pip and trying to generate the certs.

```
threema-gateway generate privateKey.txt publicKey.txt
Traceback (most recent call last):
  File "/home/pi/.local/share/virtualenvs/sms-YuepyvnI/bin/threema-gateway", line 5, in <module>
    from threema.gateway.bin.gateway_client import main
  File "/home/pi/.local/share/virtualenvs/sms-YuepyvnI/lib/python3.7/site-packages/threema/gateway/__init__.py", line 26, in <module>
    from . import _gateway
  File "/home/pi/.local/share/virtualenvs/sms-YuepyvnI/lib/python3.7/site-packages/threema/gateway/_gateway.py", line 4, in <module>
    import libnacl.encode
  File "/home/pi/.local/share/virtualenvs/sms-YuepyvnI/lib/python3.7/site-packages/libnacl/__init__.py", line 80, in <module>
    nacl = _get_nacl()
  File "/home/pi/.local/share/virtualenvs/sms-YuepyvnI/lib/python3.7/site-packages/libnacl/__init__.py", line 75, in _get_nacl
    raise OSError(msg)
OSError: Could not locate nacl lib, searched for libsodium.so, libsodium.so.23, libsodium.so.18, libsodium.so.17, libsodium.so.13, libsodium.so.10, libsodium.so.5, libsodium.so.4, 
```

I am on debian armv7l with python3.7.3.

**Comment by lgrahl** [comment]
Hi. You need to install [libsodium](https://doc.libsodium.org/installation) as mentioned in the readme.
