### ISSUE TITLE
RuntimeError with aiohttp >= 3.8

### ISSUE THREAD

**Issue by eknoes** [threema-ch/threema-msgapi-sdk-python#59]
I just updated aiohttp to 3.8.1, and my Bot was not able to receive any messages anymore:

```
2021-12-10 08:05:22,779 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "/home/bot/covidbot/venv/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    reset = await self.finish_response(request, resp, start_time)
  File "/home/bot/covidbot/venv/lib/python3.8/site-packages/aiohttp/web_app.py", line 504, in _handle
    """gunicorn compatibility"""
  File "/home/bot/covidbot/venv/lib/python3.8/site-packages/threema/gateway/e2e.py", line 212, in handle_callback
    message = await context.receive_handler(context.connection, {
  File "/home/bot/covidbot/venv/lib/python3.8/site-packages/threema/gateway/e2e.py", line 481, in receive
    key_pair = await cls.get_decrypt_key_pair(connection, parameters)
  File "/home/bot/covidbot/venv/lib/python3.8/site-packages/threema/gateway/e2e.py", line 585, in get_decrypt_key_pair
    public = await connection.get_public_key(parameters['from_id'])
  File "/home/bot/covidbot/venv/lib/python3.8/site-packages/threema/gateway/util.py", line 352, in _wrapper
    value = await func(*args, **kwargs)
  File "/home/bot/covidbot/venv/lib/python3.8/site-packages/threema/gateway/_gateway.py", line 176, in get_public_key
    response = await self._get(self.urls['get_public_key'].format(id_))
  File "/home/bot/covidbot/venv/lib/python3.8/site-packages/threema/gateway/_gateway.py", line 317, in _get
    return await self._session.get(*args, **kwargs)
  File "/home/bot/covidbot/venv/lib/python3.8/site-packages/aiohttp/client.py", line 466, in _request
    and hdrs.AUTHORIZATION in headers
  File "/home/bot/covidbot/venv/lib/python3.8/site-packages/aiohttp/helpers.py", line 701, in __enter__
    @property
RuntimeError: Timeout context manager should be used inside a task
```

Unfortunately, I currently do not have the time to look further into this, the simple solution is to sepcify `aiohttp<3.8`, this was my quick fix. Can anyone reproduce this with aiohttp >= 3.8, or is it related to my whole setup?

**Comment by lgrahl** [comment]
I totally missed this. Apologies. Is it still an issue? I'm running a slightly complex setup with aiohttp 3.8.1 and don't run into it.

**Comment by lgrahl** [comment]
I have a hunch that this is another variant of #62. You will need to create the `Connection` instance while an event loop is already running.

Feel free to reopen if this doesn't resolve your issue. But then I'll need a short reproducer example to investigate.
